# Generated by Django 5.1.7 on 2025-03-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexecution',
            name='execution_time',
            field=models.FloatField(null=True),
        ),
    ]
