version: "3.8"

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 job_scheduler.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  scheduler:
    build: .
    command: python manage.py start_scheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A job_scheduler worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: job_scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-db-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: